services:
  postgres:
    image: postgres
    container_name: postgres-dotnetHero
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${DB__PASSWORD}
      POSTGRES_DB: dotnetHero
    ports:
      - "${PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
